export { default as SectionAbout } from './SectionAbout'
export { default as SectionSkill } from './SectionSkill'
export { default as SectionFreelancing } from './SectionFreelancing'
export { default as SectionContact } from './SectionContact'
export { default as SectionProjects } from './SectionProjects'
export { default as SectionBlogs } from './SectionBlogs'